title: Westley Overcash
email: wes@wessence.com
description: I write the stories your audience retells.
url: "https://wessence.com"
baseurl: ""

author: 
  name: Westley Overcash
  twitter: westleyovercash
twitter:
  username: westleyovercash
  card: summary_large_image
image: /assets/css/images/Westley-Overcash.jpg

timezone: Europe/Prague
future: false

markdown: kramdown

paginate: 10
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  writing:
    output: true
    permalink: /writing/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
